import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { formatDate, formatTime, PatientStatusBadge } from "@/components/patient-format";
import { BLOOD_TYPE_LABELS as BLOOD_LABELS, SEX_LABELS } from "@/lib/patient-options";
import { ApiError, getPatient, type Patient } from "@/lib/api";
import { requireClinicalRole } from "@/lib/auth-context";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export default async function PatientPage({ params }: { params: Promise<{id:string}> }) { const {id}=await params; if(!UUID.test(id)) notFound(); const {user,accessToken}=await requireClinicalRole(); let patient:Patient|null=null; try{patient=await getPatient(id,accessToken);}catch(error){if(error instanceof ApiError&&error.status===401)redirect("/auth/logout?reason=expired");if(error instanceof ApiError&&error.status===403)redirect("/dashboard");if(error instanceof ApiError&&error.status===404)notFound();} return <AppShell user={user} active="patients">{patient?<PatientDetails patient={patient}/>:<p role="alert">No fue posible cargar el paciente.</p>}</AppShell>; }
export function PatientDetails({patient}:{patient:Patient}) { const details=[['Historia clínica',patient.medicalRecordNumber],['Nombre completo',`${patient.firstName} ${patient.lastName}`],['Fecha de nacimiento',formatDate(patient.birthDate)],['Hora de nacimiento',formatTime(patient.birthTime)],['Sexo',SEX_LABELS[patient.sex]],['Peso al nacer',`${patient.birthWeightGrams} g`],['Edad gestacional',`${patient.gestationalAgeWeeks} semanas + ${patient.gestationalAgeDays} días`],['Tipo sanguíneo',BLOOD_LABELS[patient.bloodType]],['Fecha de registro',formatDate(patient.createdAt)]]; return <><p className="text-sm font-medium text-cyan-700"><Link href="/patients">Pacientes</Link> / {patient.medicalRecordNumber}</p><div className="mt-5 flex items-center gap-3"><h1 className="text-3xl font-bold">{patient.firstName} {patient.lastName}</h1><PatientStatusBadge status={patient.status}/></div><dl className="mt-8 grid max-w-3xl gap-6 rounded-2xl border bg-white p-6 sm:grid-cols-2">{details.map(([label,value])=><div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl></>; }
