import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { formatDate, PatientStatusBadge } from "@/components/patient-format";
import { SEX_LABELS } from "@/lib/patient-options";
import { ApiError, getPatients, type Patient } from "@/lib/api";
import { requireClinicalRole } from "@/lib/auth-context";

export default async function PatientsPage() {
  const { user, accessToken } = await requireClinicalRole(); let patients: Patient[] | null = null;
  try { patients = await getPatients(accessToken); } catch (error) { if (error instanceof ApiError && error.status === 401) redirect("/auth/logout?reason=expired"); if (error instanceof ApiError && error.status === 403) redirect("/dashboard"); }
  return <AppShell user={user} active="patients"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-cyan-700"><Link href="/dashboard">Dashboard</Link> / Pacientes</p><h1 className="mt-2 text-3xl font-bold">Pacientes</h1><p className="mt-2 text-slate-600">Registro administrativo de recién nacidos.</p></div><Link href="/patients/new" className="rounded-xl bg-cyan-700 px-4 py-3 text-center font-semibold text-white">Nuevo paciente</Link></div>{patients === null ? <PatientError /> : patients.length === 0 ? <PatientEmpty /> : <PatientList patients={patients} />}</AppShell>;
}

export function PatientList({ patients }: { patients: Patient[] }) { return <div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Historia", "Nombre", "Nacimiento", "Sexo", "Peso", "Estado", "Acción"].map((x) => <th className="px-4 py-4" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{patients.map((p) => <tr key={p.id}><td className="px-4 py-4 font-mono text-sm">{p.medicalRecordNumber}</td><td className="px-4 py-4 font-semibold">{p.firstName} {p.lastName}</td><td className="px-4 py-4">{formatDate(p.birthDate)}</td><td className="px-4 py-4">{SEX_LABELS[p.sex]}</td><td className="px-4 py-4">{p.birthWeightGrams} g</td><td className="px-4 py-4"><PatientStatusBadge status={p.status} /></td><td className="px-4 py-4"><Link href={`/patients/${p.id}`} className="font-semibold text-cyan-700">Ver detalle</Link></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{patients.map((p) => <article className="p-5" key={p.id}><p className="font-mono text-xs text-slate-500">{p.medicalRecordNumber}</p><h2 className="mt-1 font-bold">{p.firstName} {p.lastName}</h2><p className="mt-2 text-sm text-slate-600">{formatDate(p.birthDate)} · {p.birthWeightGrams} g</p><div className="mt-4 flex justify-between"><PatientStatusBadge status={p.status} /><Link href={`/patients/${p.id}`} className="font-semibold text-cyan-700">Ver detalle</Link></div></article>)}</div></div>; }
export function PatientEmpty() { return <section className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No hay pacientes registrados.</h2><Link href="/patients/new" className="mt-5 inline-flex rounded-xl bg-cyan-700 px-4 py-3 font-semibold text-white">Registrar primer paciente</Link></section>; }
export function PatientError() { return <section role="alert" className="mt-8 rounded-2xl border border-red-200 bg-white p-8"><h2 className="font-bold">No fue posible cargar los pacientes.</h2></section>; }
