"use client";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { ApiError, createPatient } from "@/lib/api";
import { BLOOD_TYPES, BLOOD_TYPE_LABELS as BLOOD_LABELS, PATIENT_SEXES, SEX_LABELS, type BloodType, type PatientSex } from "@/lib/patient-options";
import { createClient } from "@/lib/supabase/client";

export function PatientForm() {
  const router = useRouter(); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [weight, setWeight] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const form = new FormData(event.currentTarget); const birthDate = String(form.get("birthDate")); if (birthDate > new Date().toISOString().slice(0, 10)) { setError("La fecha de nacimiento no puede estar en el futuro."); return; } setBusy(true);
    try { const supabase = createClient(); const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) { await supabase.auth.signOut(); router.replace("/login"); return; }
      const patient = await createPatient({ medicalRecordNumber: String(form.get("medicalRecordNumber")).trim().toUpperCase(), firstName: String(form.get("firstName")).trim(), lastName: String(form.get("lastName")).trim(), birthDate, birthTime: String(form.get("birthTime") || "") || undefined, sex: String(form.get("sex")) as PatientSex, birthWeightGrams: Number(form.get("birthWeightGrams")), gestationalAgeWeeks: Number(form.get("gestationalAgeWeeks")), gestationalAgeDays: Number(form.get("gestationalAgeDays")), bloodType: String(form.get("bloodType")) as BloodType }, token); router.push(`/patients/${patient.id}`); router.refresh();
    } catch (caught) { if (caught instanceof ApiError && caught.status === 401) { await createClient().auth.signOut(); router.replace("/login"); return; } const messages: Record<number,string> = { 400: "Revisa los datos del paciente.", 403: "No tienes permisos para realizar esta acción.", 409: "Ya existe un paciente con ese número de historia clínica." }; setError(caught instanceof ApiError ? messages[caught.status] ?? "No fue posible completar la operación." : "No fue posible completar la operación."); } finally { setBusy(false); }
  }
  return <form onSubmit={submit} className="mt-7 max-w-3xl space-y-6 rounded-2xl border border-slate-200 bg-white p-6"><div className="grid gap-5 sm:grid-cols-2"><Field name="medicalRecordNumber" label="Número de historia clínica" /><Field name="firstName" label="Nombre" /><Field name="lastName" label="Apellido" /><Field name="birthDate" label="Fecha de nacimiento" type="date" /><Field name="birthTime" label="Hora de nacimiento (opcional)" type="time" required={false} /><label className="text-sm font-semibold">Sexo<select name="sex" className="mt-2 w-full rounded-xl border p-3">{PATIENT_SEXES.map((x) => <option key={x} value={x}>{SEX_LABELS[x]}</option>)}</select></label><div><Field name="birthWeightGrams" label="Peso al nacer (g)" type="number" min="1" max="20000" onChange={(value) => setWeight(value)} />{Number(weight) > 0 && <p className="mt-1 text-xs text-slate-500">{(Number(weight)/1000).toFixed(2)} kg</p>}</div><Field name="gestationalAgeWeeks" label="Edad gestacional (semanas)" type="number" min="0" max="60" /><Field name="gestationalAgeDays" label="Edad gestacional (días)" type="number" min="0" max="6" /><label className="text-sm font-semibold">Tipo sanguíneo<select name="bloodType" className="mt-2 w-full rounded-xl border p-3">{BLOOD_TYPES.map((x) => <option key={x} value={x}>{BLOOD_LABELS[x]}</option>)}</select></label></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<button disabled={busy} className="rounded-xl bg-cyan-700 px-5 py-3 font-semibold text-white disabled:opacity-60">{busy ? "Registrando…" : "Registrar paciente"}</button></form>;
}
function Field({ name, label, type="text", required=true, min, max, onChange }: { name:string; label:string; type?:string; required?:boolean; min?:string; max?:string; onChange?:(value:string)=>void }) { return <label className="text-sm font-semibold">{label}<input aria-label={label} name={name} type={type} required={required} min={min} max={max} onChange={(e) => onChange?.(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3" /></label>; }
