CREATE TYPE "telemetry_quality" AS ENUM ('GOOD', 'SUSPECT', 'INVALID');

CREATE TABLE "telemetry" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "device_id" UUID NOT NULL,
    "sensor_id" UUID NOT NULL,
    "measurement_definition_id" UUID NOT NULL,
    "incubator_id" UUID NOT NULL,
    "admission_id" UUID,
    "value" DOUBLE PRECISION NOT NULL,
    "measured_at" TIMESTAMPTZ(6) NOT NULL,
    "received_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sequence" BIGINT NOT NULL,
    "boot_id" UUID NOT NULL,
    "quality" "telemetry_quality" NOT NULL DEFAULT 'GOOD',
    CONSTRAINT "telemetry_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "telemetry_sequence_check" CHECK ("sequence" >= 0),
    CONSTRAINT "telemetry_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "telemetry_sensor_id_fkey" FOREIGN KEY ("sensor_id") REFERENCES "sensors"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "telemetry_measurement_definition_id_fkey" FOREIGN KEY ("measurement_definition_id") REFERENCES "measurement_definitions"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "telemetry_incubator_id_fkey" FOREIGN KEY ("incubator_id") REFERENCES "incubators"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "telemetry_admission_id_fkey" FOREIGN KEY ("admission_id") REFERENCES "admissions"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "telemetry_device_id_boot_id_sequence_sensor_id_measurement_definition_id_key" ON "telemetry"("device_id", "boot_id", "sequence", "sensor_id", "measurement_definition_id");
CREATE INDEX "telemetry_sensor_id_measured_at_idx" ON "telemetry"("sensor_id", "measured_at" DESC);
CREATE INDEX "telemetry_device_id_measured_at_idx" ON "telemetry"("device_id", "measured_at" DESC);
CREATE INDEX "telemetry_incubator_id_measured_at_idx" ON "telemetry"("incubator_id", "measured_at" DESC);
CREATE INDEX "telemetry_admission_id_measured_at_idx" ON "telemetry"("admission_id", "measured_at" DESC);
CREATE INDEX "telemetry_measurement_definition_id_measured_at_idx" ON "telemetry"("measurement_definition_id", "measured_at" DESC);
CREATE INDEX "telemetry_sensor_id_measurement_definition_id_measured_at_idx" ON "telemetry"("sensor_id", "measurement_definition_id", "measured_at" DESC);
